export const DD_SCENARIO_RECOMMENDATIONS = [
  {
    key: 'AI',
    direction: 'AI',
    scenario: 'AI',
    info: 'Обучение и калибровка AI-моделей, настройка и тестирование AI-агентов',
    sourceTool: 'Bootcamp',
    recommendation: 'Рекомендуем согласованить с HR-партнёром участие аналитиков в AI Bootcamp',
    resources: [{label: 'AI Bootcamp', href: 'https://bootcamp.pcbltools.ru/task/1585206?courseId=1176', placement: 'inline'}],
  },
  {
    key: 'customer_experience_analytics',
    direction: 'Аналитика',
    scenario: 'Аналитика клиентского опыта',
    info: 'Анализ поведения пользователей, пути клиента, воронки, когортный анализ.',
    sourceTool: 'OpenCode',
    recommendation: 'Рекомендуем для оптимизации работы с кодом попробовать OpenCode в Datalab AI — аналог Claude. Посмотрите рекомендации по ссылке. Для оценки клиентских путей рекомендуем использовать LossHunter и CJExplorer. Также предлагаем воспользоваться AI Toolkit «Продуктовый аналитик».',
    resources: [
      {label: 'ссылке', href: 'https://mapp.sberbank.ru/b2cda/page/394333', placement: 'inline'},
      {label: 'LossHunter', href: 'https://losshunter.ru', placement: 'inline'},
      {label: 'CJExplorer', href: 'https://cjxplorer.com/', placement: 'inline'},
      {label: 'Продуктовый аналитик', action: 'product-analyst-access', placement: 'inline'},
    ],
  },
  {
    key: 'methodology_dev',
    direction: 'Аналитика',
    scenario: 'Разработка методологии',
    info: 'Разработка правил расчета метрик, согласование определений с бизнесом.',
    sourceTool: 'FeatureStore',
    recommendation: 'Рекомендуем оформлять согласованные методологии как переиспользуемые артефакты во FeatureStore',
    resources: [{label: 'FeatureStore', href: 'https://confluence.sberbank.ru/pages/viewpage.action?pageId=21560591134', placement: 'inline'}],
  },
  {
    key: 'metrics_calculation',
    direction: 'Аналитика',
    scenario: 'Расчет метрик',
    info: 'Разработка скриптов или процедур для расчета ключевых показателей (часто на регулярной основе)',
    sourceTool: 'OpenCode',
    recommendation: 'Рекомендуем использовать OpenCode в Datalab AI для подготовки, рефакторинга и документирования расчётных скриптов.',
    resources: [{label: 'ссылке', href: 'https://mapp.sberbank.ru/b2cda/page/394333'}],
  },
  {
    key: 'exports_to_excel',
    direction: 'Выгрузка',
    scenario: 'Выгрузки в Excel',
    info: 'Формирование выгрузки по разовому запросу. Данные без глубокой обработки или «как есть» из источника',
    sourceTool: 'OpenCode',
    recommendation: 'Рекомендуем переводить повторяющиеся выгрузки в параметризованные скрипты с помощью OpenCode в Datalab AI.',
    resources: [{label: 'ссылке', href: 'https://mapp.sberbank.ru/b2cda/page/394333'}],
  },
  {
    key: 'excel_automatic_reports',
    direction: 'Выгрузка',
    scenario: 'Автоматизированные отчеты',
    info: 'Отчеты, формируемые автоматически по расписанию или триггеру. Настройка производится однократно через скрипт (SQL, Python, ETL) или прямое подключение к базе данных. После настройки обновление данных происходит без ручного вмешательства',
    sourceTool: 'AirFlow и AI Note в ЛД',
    recommendation: 'Рекомендуем планировать регулярные расчёты в AirFlow, а AI Note в ЛД использовать для ускорения разработки и проверки кода.',
    resources: [{label: 'ссылке', href: 'https://mapp.sberbank.ru/greenlab/page/994'}],
  },
  {
    key: 'data_marts',
    direction: 'Данные и автоматизация',
    scenario: 'Данные и автоматизация',
    info: 'Проектирование и создание витрин данных для отчетов или дашбордов (ETL/ELT процессы).',
    sourceTool: 'Стандарты создания витрин',
    recommendation: 'Рекомендуем начинать новые витрины со стандартного маршрута проектирования, для базовых витрин использовать готовый шаблон и заранее подключать CDO юнита.',
    resources: [
      {label: 'основной инструкции', href: 'https://confluence.sberbank.ru/pages/viewpage.action?pageId=23607905561'},
      {label: 'шаблону базовых витрин', href: 'https://confluence.delta.sbrf.ru/pages/viewpage.action?pageId=17033528890'},
      {label: 'контактам CDO', href: 'https://confluence.sberbank.ru/pages/viewpage.action?pageId=12446342550'},
    ],
  },
  {
    key: 'manual_data_quality_control',
    direction: 'Данные и автоматизация',
    scenario: 'Ручной ККД',
    info: 'Ручной контроль качества данных, сверка, исправление ошибок в данных вручную.',
    sourceTool: 'Централизованный сервис ККД',
    recommendation: 'Рекомендуем выбрать один повторяющийся контроль и пилотно автоматизировать его через централизованный сервис ККД, отслеживая результат в отчёте B2C.',
    resources: [
      {label: 'сервису ККД', href: 'https://mapp.sberbank.ru/sberdataproducts/page/49403'},
      {label: 'отчёту B2C', href: 'https://navigator.sigma.sbrf.ru/gdash/1000000237/1000002468'},
    ],
  },
  {
    key: 'root_cause_analysis',
    direction: 'Исследования',
    scenario: 'Анализ корневых причин',
    info: 'Выявление корневых причин отклонений или проблем в данных/процессах с помощью исследовательских и статистических методов',
    sourceTool: 'DataLab Pro|OpenCode',
    recommendation: 'Рекомендуем проводить анализ корневых причин в DataLab Pro, а OpenCode использовать для ускорения подготовки и проверки исследовательского кода.',
    resources: [{label: 'ссылке', href: 'https://mapp.sberbank.ru/b2cda/page/394333'}],
  },
  {
    key: 'growth_factors_research',
    direction: 'Исследования',
    scenario: 'Поиск точек роста',
    info: 'Выявление скрытых зависимостей (что влияет на LTV, Retention). Часто требует статистических методов.',
    sourceTool: 'OpenCode',
    recommendation: 'Рекомендуем использовать OpenCode в Datalab AI для ускорения разведочного анализа, проверки гипотез и воспроизводимого расчёта факторов роста.',
    resources: [{label: 'ссылке', href: 'https://mapp.sberbank.ru/b2cda/page/394333'}],
  },
  {
    key: 'business_planning',
    direction: 'Моделирование',
    scenario: 'Бизнес-планирование',
    info: 'Построение прогнозов, план-факт анализ, моделирование сценариев развития.',
    sourceTool: 'OpenCode',
    recommendation: 'Рекомендуем использовать OpenCode в Datalab AI для подготовки сценарных моделей, автоматизации план-факт расчётов и документирования допущений.',
    resources: [{label: 'ссылке', href: 'https://mapp.sberbank.ru/b2cda/page/394333'}],
  },
  {
    key: 'financial_impact_estimation',
    direction: 'Моделирование',
    scenario: 'Оценка финансового эффекта',
    info: 'Финансово-экономическое обоснование, прогноз окупаемости, расчет юнит-экономики гипотезы, расчет эффекта от проделанных акций/кампаний.',
    sourceTool: 'АВ тестирование',
    recommendation: 'Рекомендуем подтверждать финансовый эффект через дизайн A/B-теста: заранее фиксировать основную метрику, горизонт наблюдения и правила расчёта эффекта.',
  },
  {
    key: 'unknown',
    direction: 'Неизвестно',
    scenario: 'Невозможно разметить',
    info: 'Невозможно выполнить разметку (назначить категорию, сценарий, метку) из-за низкого качества исходного описания: недостаточно деталей, размытые формулировки, отсутствие ключевых параметров. Требуется доработка описания автором.',
    sourceTool: '',
    recommendation: 'Рекомендуем повысить качество описаний задач для более корректного мапинга задач с нашей стороны',
  },
  {
    key: 'project_management',
    direction: 'Организационное',
    scenario: 'Project Management',
    info: 'Управление сроками, задачами, командой в рамках аналитических проектов.',
    sourceTool: 'переход в jira|Сбертрек',
    recommendation: 'Рекомендуем вести сроки, владельцев и зависимости аналитических проектов в Jira или Сбертреке и отказаться от параллельных ручных списков.',
  },
  {
    key: 'social_communications',
    direction: 'Организационное',
    scenario: 'Встречи, коммуникации',
    info: 'Участие во внутренних и внешних встречах, консультирование коллег и заказчиков, согласование требований с подрядчиками, решение операционных и организационных вопросов',
    sourceTool: 'Использование Автопротокола в jass',
    recommendation: 'Рекомендуем использовать Автопротокол для встреч, а решения, владельцев и сроки переносить из саммари в трекер задач.',
    resources: [{label: 'ссылке', href: 'https://potok.sber.ru/notes/summary?utm_source=mail&utm_campaign=winback'}],
  },
  {
    key: 'employee_trainings',
    direction: 'Организационное',
    scenario: 'Обучение сотрудников',
    info: 'Онбординг новичков, проведение лекций/вебинаров по аналитике.',
    sourceTool: 'Bootcamp',
    recommendation: 'Рекомендуем включить Bootcamp в план развития команды и закреплять обучение практическим заданием на данных продукта.',
  },
  {
    key: 'knowledge_base_maintenance',
    direction: 'Организационное',
    scenario: 'Формирование базы знаний',
    info: 'Написание документации, глоссария, поддержание гигиены в Confluence/M-App',
    sourceTool: '',
    recommendation: 'Рекомендуем назначить владельцев ключевых разделов базы знаний, ввести срок пересмотра материалов и единый шаблон описания аналитических артефактов.',
  },
  {
    key: 'business_requirements_composing',
    direction: 'Организационное',
    scenario: 'Формирование БТ/ТЗ',
    info: 'Формализация задач от бизнеса в техническое задание для разработки.',
    sourceTool: 'Использование Автопротокола в jass',
    recommendation: 'Рекомендуем собирать требования через Автопротокол, а затем фиксировать в БТ/ТЗ решения, ограничения, владельцев и критерии приёмки.',
    resources: [{label: 'ссылке', href: 'https://potok.sber.ru/notes/summary?utm_source=mail&utm_campaign=winback'}],
  },
  {
    key: 'excel_reports',
    direction: 'Отчеты вне BI',
    scenario: 'Отчеты в Excel',
    info: 'Создание структурированных отчетов в Excel.',
    sourceTool: 'EX-EL',
    recommendation: 'Рекомендуем оценить EX-EL как основной инструмент для типовых Excel-отчётов и начать с одного регулярного отчёта с наибольшими трудозатратами.',
    resources: [{label: 'EX-EL', action: 'ex-el-access', placement: 'inline'}],
  },
  {
    key: 'presentations',
    direction: 'Отчеты вне BI',
    scenario: 'Презентации',
    info: 'Расчет и упаковка выводов в слайды (PowerPoint) для руководства или контрагентов.',
    sourceTool: 'EX-EL',
    recommendation: 'Рекомендуем использовать EX-EL для подготовки повторяющихся расчётных блоков, оставляя аналитику выводов и управленческий нарратив за владельцем материала.',
    resources: [{label: 'EX-EL', action: 'ex-el-access', placement: 'inline'}],
  },
  {
    key: 'dashboard_improvements',
    direction: 'Разработка и поддержка BI',
    scenario: 'Доработки дашбордов',
    info: 'Проектирование и создание витрин данных для отчетов или дашбордов (ETL/ELT процессы).',
    sourceTool: 'курс Навигатора/Продуктовая аналитика',
    recommendation: 'Рекомендуем направить владельцев дашбордов на курс Навигатора или продуктовой аналитики и применить обучение на ближайшей доработке.',
    resources: [{label: 'ссылке', href: 'https://confluence.sberbank.ru/display/NAV'}],
  },
  {
    key: 'dashboard_migration',
    direction: 'Разработка и поддержка BI',
    scenario: 'Миграция дешбордов',
    info: 'Перенос существующих дашбордов и отчетов с текущей BI-платформы на целевую BI-систему. Включает: анализ исходных дашбордов, перепроектирование моделей данных под целевую платформу, перенос или пересоздание графиков и фильтров, валидацию совпадения метрик с исходными отчетами, настройку прав доступа и обновления данных. По завершении — тестирование и сдача в эксплуатацию',
    sourceTool: 'курс Навигатора/Продуктовая аналитика',
    recommendation: 'Рекомендуем до миграции пройти курс Навигатора или продуктовой аналитики, затем провести инвентаризацию метрик и зафиксировать критерии сверки со старым дашбордом.',
    resources: [{label: 'ссылке', href: 'https://confluence.sberbank.ru/display/NAV'}],
  },
  {
    key: 'dashboard_manual_data_update',
    direction: 'Разработка и поддержка BI',
    scenario: 'Ручное обновление данных',
    info: 'Расчет и ручная поставка данных в BI',
    sourceTool: 'Продуктовая аналитика',
    recommendation: 'Рекомендуем обучить владельца отчёта продуктовой аналитике и составить план перевода ручной поставки на расписание или автоматический триггер.',
  },
  {
    key: 'BI_bugfix',
    direction: 'Разработка и поддержка BI',
    scenario: 'Фикс багов в BI',
    info: 'Исправление ошибок в формулах на стороне Навигатора',
    sourceTool: '',
    recommendation: 'Рекомендуем ввести чек-лист проверки формул, тестовый набор контрольных значений и разбор повторяющихся причин ошибок перед публикацией в Навигаторе.',
  },
];
